from xxhash import xxh64
from server.storage.indexes.types.interfaces import Insertable, Deletable, Updatable, Searchable

class ExtendibleHashingFile(Insertable, Deletable, Updatable, Searchable):
    def __init__(self, idx_filename: str, data_type, key_len: int, bucket_size: int = 10) -> None: ...   
    def insert(self, key: any, value: any, **args) -> bool: ...
    def delete(self, key: any) -> any: ...
    def delete_all(self, key: any) -> any: ...
    def update(self, key: any) -> bool: ...
    def get_all_keys(self) -> list[any]: ...
    def get_all_records(self) -> list[any]: ...
    def search(self, key: any) -> any: ...
    def search_record(self, key: any) -> any: ...
    def exist(self, key: any) -> bool: ...