from server.interfaces.methods import Insertable, Deletable, Updatable, Searchable
from server.types.base import DataType

class HeapFile(Insertable, Deletable, Updatable, Searchable):
    def __init__(self, heap_filename: str) -> None: ...   
    def insert(self, key: DataType, value: DataType, **args) -> bool: ...
    def delete(self, key: DataType) -> any: ...
    def delete_all(self, key: DataType) -> any: ...
    def update(self, key: DataType, new_key: DataType) -> bool: ...
    def get_all_keys(self) -> list[int]: ...
    def get_all_records(self) -> list[DataType]: ...
    def search(self, key: DataType) -> int: ...
    def search_record(self, key: DataType) -> DataType: ...
    def exist(self, key: DataType) -> bool: ...