from server.interfaces.methods import Insertable, Deletable, Updatable, Searchable

class HeapFile(Insertable, Deletable, Updatable, Searchable):
    def __init__(self, heap_filename: str) -> None: ...   
    def insert(self, key: any, value: any, **args) -> bool: ...
    def delete(self, key: any) -> any: ...
    def delete_all(self, key: any) -> any: ...
    def update(self, key: any) -> bool: ...
    def get_all_keys(self) -> list[any]: ...
    def get_all_records(self) -> list[any]: ...
    def search(self, key: any) -> any: ...
    def search_record(self, key: any) -> any: ...
    def exist(self, key: any) -> bool: ...